apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-providers
  namespace: grafana
data:
  providers.yaml: |+
    apiVersion: 1
    providers:
    - name: 'Dashboard provider'
      ordId: 1
      folder: ''
      type: file
      options:
        path: /etc/grafana/dashboards
